### ISSUE TITLE
Interpreter ignoriert Tabulator (\t) nicht

### ISSUE THREAD

**Issue by oskmasi** [matthejue/RETI-Emulator#7]
Betrachten Sie folgendes Programm:

program.reti:
`AND IN1 IN2	# My comment...`

./program.reti:1: SyntaxError: Invalid register "IN2	"

Leider wird das ganze von Markdown falsch gerendert, es befindet sich jedoch der tab char zwischen `IN2` und `# My comment`.

Ersetzt man das Tabulatorzeichen nach dem Statement mit Leerzeichen, so existiert kein Problem. Das selbe Verhalten sollte auch nach `\t` auftreten, da so Kommentare besser eingerückt werden können.
Ein ähnliches Problem tritt auf, setzt man einen Tabulator nach einen Immediate (bspw. bei `STOREIN A B i [TAB] # Kommentar...`).

**Comment by matthejue** [comment]
Tab sollte jetzt mit dem neusten Commit unterstützt sein. Diese Änderung wird bisher nur bei der globalen Installation sichtbar, bei der lokalen Installation muss für die Änderung noch auf den nächsten Release abgewartet werden.

Cheers und eine schönen Abend dir noch.

**Comment by matthejue** [comment]
Tab sollte jetzt mit dem Commit: https://github.com/matthejue/RETI-Interpreter/commit/1bf730ce932502c011513a42b04fd6257a01f5bd unterstützt sein. Diese Änderung wird bisher nur bei der globalen Installation sichtbar, bei der lokalen Installation muss für die Änderung noch auf den nächsten Release abgewartet werden.

Cheers und eine schönen Abend dir noch.
